### ISSUE TITLE
关于async方法和Task<T>的一些问题

### ISSUE THREAD

**Issue by Executor-Cheng** [SofiaXu/Rimirin#1]
https://github.com/SofiaXu/Rimirin/blob/0206441e348e57e826424bf908d1872459ed5e53/Rimirin/Handlers/GachaHandler.cs#L40
https://github.com/SofiaXu/Rimirin/blob/0206441e348e57e826424bf908d1872459ed5e53/Rimirin/Handlers/GarupaEventHandler.cs#L28
`async void`方法中的异常无法被caller捕获, 也就是说异常会被CLR处理导致应用程序退出

https://github.com/SofiaXu/Rimirin/blob/0206441e348e57e826424bf908d1872459ed5e53/Rimirin/Plugins/GroupPlugin.cs#L39
可以使用`Task.FromResult<TResult>`方法替代使用委托的`Task<T>`构造函数

**Comment by SofiaXu** [comment]
已改，感谢大佬指点
